### ISSUE TITLE
When players are frozen then log out they are banned.  They should just remain frozen when they log back in

### ISSUE THREAD

**Issue by Klawdek** [Qballl/StaffPlus#146]
It would be nice rather than banning if frozen players who log out are just frozen if they log back in.  There should also be some kind of time limit that can be set in the config.  This would allow lower level staff that does not have the ability to ban to still use this plugin and higher level staff decides if the person that was frozen should be banned or not.  

It does not seem possible to change the banning when logging out while frozen as I tried to change the config option:      logout-commands: ban %player%  to     logout-commands:  
And it just put the ban command back in when I restarted server.

**Comment by Azoraqua** [comment]
> It does not seem possible to change the banning when logging out while frozen as I tried to change the config option: logout-commands: ban %player% to logout-commands:
> And it just put the ban command back in when I restarted server.
The server has to be offline when editing otherwise it'll get resetted.

**Comment by garagepoort** [comment]
Try placing this inside your configuration: 
```
logout-commands: ''
```

If you leave it empty it will fall back on the default config. So the quotes are important here

The reason for the ban command being overwritten again is because there is an issue with the configuration version.
The version in your config is probably higher than the one in the code base. A quick fix for this is the change your config version from 6205 to 6204. But better is if the config version would be fixed in the code.
