### ISSUE TITLE
Vanish tweak

### ISSUE THREAD

**Issue by lolli62** [Qballl/StaffPlus#40]
Is it possible to make it so that when a staff goes into Vanish, 1) they can't pick up items from the ground, and 2) anything held in hand can't be seen by the regular members?
Thank you

**Comment by Qballl** [comment]
The not picking up items would be an easy thing, but the items will be hard I will probably have to use the packet for player being visible and just stop sending.

**Comment by lolli62** [comment]
Thank you for a quick reply!
Is it all possible though? It would be soo useful!

**Comment by Qballl** [comment]
It is but hard and based on the number of requests for it I will see about adding it in the near future.

**Comment by Damdamdu95** [comment]
If it's too hard, why not make some kind of alternative such as replacing the TOTAL VANISH with a specific command that would run instead of the TOTAL VANISH such as "/v'" (however, the vanish of StaffPlus should be disabled). Otherwise, I have an idea that might be interesting, it would be to make a kind of command that runs automatically and who can change depending on whether the /staff is enabled or not. 

Illustration : 
command_on_staff: true
  staff_on: 'command_example on'
  staff_off: 'command_example off'

PS: Sorry for my bad english, I'm French.

**Comment by Qballl** [comment]
I have the second part done I will do the first one now

**Comment by Qballl** [comment]
Vanish tweaks are done
